
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId = "seasonhud"
    version = "${file.jarVersion}"
    displayName = "SeasonHUD"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/seasonhud"
    logoFile= "SeasonHUD.png"
    logoBlur = true
    authors="IanAnderson"
    description ='''
    This is an addon for SereneSeasons that displays the current season on the HUD or under a minimap'''

[[dependencies.seasonhud]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonhud]]
    modId="minecraft"
    mandatory=true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.seasonhud]]
    modId = "sereneseasons"
    mandatory = true
    versionRange = "[1.19-8.0.0.19,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.seasonhud]]
    modId = "xaerominimap"
    mandatory = false
    versionRange = "[23.1.0,)"
    ordering = "AFTER"
    side = "CLIENT"